In [141]:
import torch 
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1337)

def attention(q, k, v):
    score = q @ k.transpose(-2, -1) # (3, 16) @ (16, 3) -> (3, 3)
    score = score / d_k**0.5 
    print(score)
    weights = F.softmax(score, dim=-1) #shape: (3, 3)
    out = weights @ v # shape: (3, 3) @ (3, 16) -> (3, 16)
    return out, weights

dim = 16
d_k = 4
emb = torch.randn(3, dim) # shape (3, 2)

q = torch.randn(dim, d_k) # shape: (16, 4)
k = torch.randn(dim, d_k) # shape: (16, 4)
v = torch.randn(dim, d_k) # shape: (16, 4)

w_q = (emb @ q) / dim**0.5 # shape: (3, 16) @ (16, 4) -> (3, 4)
w_k = (emb @ k) / dim**0.5 # shape: (3, 16) @ (16, 4) -> (3, 4)
w_v = (emb @ v) / dim**0.5# shape: (3, 16) @ (16, 4) -> (3, 4)

out, weights = attention(q, k , v)
print(weights)

print(out)


tensor([[ 0.0401,  0.5243,  0.3122],
        [-0.6108,  1.3484,  1.5902],
        [-0.1929,  0.7108,  0.5840]])
tensor([[0.2541, 0.4124, 0.3336],
        [0.0584, 0.4142, 0.5275],
        [0.1772, 0.4374, 0.3853]])
tensor([[-0.2342, -0.6040, -0.2128, -0.2613],
        [ 0.0296, -0.1780, -0.3695, -0.4490],
        [-0.1801, -0.5080, -0.2865, -0.3632]])


In [148]:
out.shape

torch.Size([3, 4])