In [54]:
import torch    
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1337)

def attention(q, k, v):
    score = q @ k.transpose(-2, -1) # (h, vocab_size, d_k) @ (h, d_k, vocab_size) -> (h, vocab_size, vocab_size) 
    score = score / q.shape[-1]**0.5 # shape (h, vocab_size, vocab_size)
    weights = F.softmax(score, dim=-1) #shape: (h, vocab_size, vocab_size)
    out = weights @ v # shape: (h, vocab_size, vocab_size) @ (h, vocab_size, d_k) -> (h, vocab_size, d_k)
    return out, weights

def multi_head_attention(emb, w_q, w_k, w_v, w_o, n_heads):
    vocab_size, dim = emb.shape
    d_k = dim // n_heads

    q = emb @ w_q # (vocab_size, dim) @ (dim, dim) -> (vocab_size, dim)
    k = emb @ w_k # (vocab_size, dim) @ (dim, dim) -> (vocab_size, dim)
    v = emb @ w_v # (vocab_size, dim) @ (dim, dim) -> (vocab_size, dim)

    # split into heads: (vocab_size, dim) -> (vocab_size, h, d_k) -> (h, vocab_size, d_k)
    # note that h * d_k -> dim
    q = q.view(vocab_size, n_heads, d_k).transpose(0, 1) 
    k = k.view(vocab_size, n_heads, d_k).transpose(0, 1)
    v = v.view(vocab_size, n_heads, d_k).transpose(0, 1)

    out, weights = attention(q, k, v)

    # merge heads back: (h, vocab_size, d_k) -> (vocab_size, h, d_k) -> (vocab_size, dim)
    out = out.transpose(0, 1).contiguous().view(vocab_size, dim)

    final = out @ w_o
    return final, weights

def layer_norm(x, gamma, beta, eps=1e-5):
    mean = x.mean(dim=1, keepdim=True) # get mean across rows - get the mean of each token's representation
    std = x.std(dim=1, keepdim=True) # get std across rows - get the std of each token's representation 
    x_norm = (x - mean) / (std + eps) # layer norm 
    return gamma * x_norm + beta 

def positional_encoding(seq_len, dim):
    pos = torch.arange(seq_len).unsqueeze(1) # shape: (seq_len, 1)
    i = torch.arange(0, dim, 2) # shape: (dim/2,)
    freq = 1.0 / (10000 ** (i / dim)) # shape: (dim/2,)
    angles = pos * freq # shape: (seq_len, dim/2)
    pe = torch.zeros(seq_len, dim) # shape: (seq_len, dim)
    pe[:, 0::2] = torch.sin(angles) # apply sin to even indices
    pe[:, 1::2] = torch.cos(angles) # apply cos to odd indices
    return pe

n_heads = 4
dim = 16
emb = torch.randn(3, dim) # shape (3, 16)

w_q = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim)
w_k = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim)
w_v = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim)
w_o = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim)

gamma = torch.ones(dim)
beta = torch.zeros(dim)

attn_out, weights = multi_head_attention(emb, w_q, w_k, w_v, w_o, n_heads)
x = layer_norm(emb + attn_out, gamma, beta) # residual connection + layer norm

# Parameters for the feed forward network
ffn_w1 = torch.randn(dim, dim * 4) / (dim**0.5) # shape: (dim, dim * 4)
ffn_b1 = torch.randn(dim * 4) / (dim**0.5) # shape: (dim * 4)
ffn_w2 = torch.randn(dim * 4, dim) / (dim**0.5) # shape: (dim * 4, dim)
ffn_b2 = torch.randn(dim) / (dim**0.5) # shape: (dim)

def feed_forward(x, w1, b1, w2, b2):
    x = F.relu(x @ w1 + b1) # shape: (vocab_size, dim * 4)
    x = x @ w2 + b2 # shape: (vocab_size, dim)
    return x

ffn_out = feed_forward(x, ffn_w1, ffn_b1, ffn_w2, ffn_b2)

gamma1 = torch.ones(dim)
beta1 = torch.zeros(dim)

ffn_out = layer_norm(x + ffn_out, gamma1, beta1) # residual connection + layer norm


def encoder_block(emb, w_q, w_k, w_v, w_o, n_heads, gamma, beta, ffn_w1, ffn_b1, ffn_w2, ffn_b2):
    attn_out, weights = multi_head_attention(emb, w_q, w_k, w_v, w_o, n_heads)
    x = layer_norm(emb + attn_out, gamma, beta) # residual connection + layer norm
    ffn_out = feed_forward(x, ffn_w1, ffn_b1, ffn_w2, ffn_b2)
    gamma1 = torch.ones(x.shape[1])
    beta1 = torch.zeros(x.shape[1])
    ffn_out = layer_norm(x + ffn_out, gamma1, beta1) # residual connection + layer norm
    return ffn_out

# block 1 
x1 = encoder_block(emb, w_q, w_k, w_v, w_o, n_heads, gamma, beta, ffn_w1, ffn_b1, ffn_w2, ffn_b2)
#X1.shape


# Block 2 - weights, freshly initialized, same shapes as before
w_q2 = torch.randn(dim, dim) / dim**0.5
w_k2 = torch.randn(dim, dim) / dim**0.5
w_v2 = torch.randn(dim, dim) / dim**0.5
w_o2 = torch.randn(dim, dim) / dim**0.5

gamma_2 = torch.ones(dim)
beta_2 = torch.zeros(dim)

# Parameters for the feed forward network
ffn_w2_1 = torch.randn(dim, dim * 4) / (dim**0.5) # shape: (dim, dim * 4)
ffn_b2_1 = torch.randn(dim * 4) / (dim**0.5) # shape: (dim * 4)
ffn_w2_2 = torch.randn(dim * 4, dim) / (dim**0.5) # shape: (dim * 4, dim)
ffn_b2_2 = torch.randn(dim) / (dim**0.5) # shape: (dim)

#x2 = encoder_block(x1, w_q2, w_k2, w_v2, w_o2, n_heads, gamma_2, beta_2, ffn_w2_1, ffn_b2_1, ffn_w2_2, ffn_b2_2)

#x2.shape


torch.Size([3, 16])

In [150]:
torch.manual_seed(0)

vocab_size = 10
seq_len = 4

def make_example(vocab_size, seq_len):
    x = torch.randint(0, vocab_size, (seq_len,))
    y = x.flip(0)
    
    return x, y

x, y = make_example(vocab_size, seq_len)

In [ ]:

torch.manual_seed(1337)

# ----------------------Positional Encoding----------------------
def positional_encoding(seq_len, dim):
    pos = torch.arange(seq_len).unsqueeze(1) # shape: (seq_len, 1)
    i = torch.arange(0, dim, 2) # shape: (dim/2,)
    freq = 1.0 / (10000 ** (i / dim)) # shape: (dim/2,)
    angles = pos * freq # shape: (seq_len, dim/2)
    pe = torch.zeros(seq_len, dim) # shape: (seq_len, dim)
    pe[:, 0::2] = torch.sin(angles) # apply sin to even indices
    pe[:, 1::2] = torch.cos(angles) # apply cos to odd indices
    return pe


# ----------------------Attention----------------------

def attention(q, k, v):
    score = q @ k.transpose(-2, -1) # (h, vocab_size, d_k) @ (h, d_k, vocab_size) -> (h, vocab_size, vocab_size) 
    score = score / q.shape[-1]**0.5 # shape (h, vocab_size, vocab_size)
    weights = F.softmax(score, dim=-1) #shape: (h, vocab_size, vocab_size)
    out = weights @ v # shape: (h, vocab_size, vocab_size) @ (h, vocab_size, d_k) -> (h, vocab_size, d_k)
    return out, weights


def multi_head_attention(emb, w_q, w_k, w_v, w_o, n_heads):
    vocab_size, dim = emb.shape
    d_k = dim // n_heads

    q = emb @ w_q # (vocab_size, dim) @ (dim, dim) -> (vocab_size, dim)
    k = emb @ w_k # (vocab_size, dim) @ (dim, dim) -> (vocab_size, dim)
    v = emb @ w_v # (vocab_size, dim) @ (dim, dim) -> (vocab_size, dim)

    # split into heads: (vocab_size, dim) -> (vocab_size, h, d_k) -> (h, vocab_size, d_k)
    # note that h * d_k -> dim
    q = q.view(vocab_size, n_heads, d_k).transpose(0, 1) 
    k = k.view(vocab_size, n_heads, d_k).transpose(0, 1)
    v = v.view(vocab_size, n_heads, d_k).transpose(0, 1)

    out, weights = attention(q, k, v)

    # merge heads back: (h, vocab_size, d_k) -> (vocab_size, h, d_k) -> (vocab_size, dim)
    out = out.transpose(0, 1).contiguous().view(vocab_size, dim)

    final = out @ w_o
    return final, weights

# ----------------------Layer Normalization----------------------
def layer_norm(x, gamma, beta, eps=1e-5):
    mean = x.mean(dim=1, keepdim=True) # get mean across rows - get the mean of each token's representation
    std = x.std(dim=1, keepdim=True) # get std across rows - get the std of each token's representation 
    x_norm = (x - mean) / (std + eps) # layer norm 
    return gamma * x_norm + beta 

#-----------------------Feed Forward Network----------------------

def feed_forward(x, w1, b1, w2, b2):
    x = F.relu(x @ w1 + b1) # shape: (vocab_size, dim * 4) # (4, 64)
    x = x @ w2 + b2 # shape: (vocab_size, dim) # (4, 16)
    return x


#----------------------Encoder Block------------------------------------

# attention heads
n_heads = 4

# Embedding matrix
C = torch.randn(vocab_size, dim) / (dim**0.5) # shape: (vocab_size, dim) => (10, 16)

emb = C[x] # shape: (seq_len, dim) (4, 16)

pe = positional_encoding(seq_len, dim) # shape: (seq_len, dim) (4, 16)
emb_pe = emb + pe # shape: (seq_len, dim) (4, 16)


# Weight matrices for multi-head attention
w_q = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim) -> (16, 16)
w_k = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim) -> (16, 16)
w_v = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim) -> (16, 16)
w_o = torch.randn(dim, dim) / dim**0.5 # shape: (dim, dim) -> (16, 16)

# Layer normalization parameters
gamma = torch.ones(dim) # shape: (dim) -> (16,)
beta = torch.zeros(dim) # shape: (dim) -> (16,)

# Parameters for the feed forward network
ffn_w1 = torch.randn(dim, dim * 4) / (dim**0.5) # shape: (dim, dim * 4) # (16, 64)
ffn_b1 = torch.randn(dim * 4) / (dim**0.5) # shape: (dim * 4) # (64,)
ffn_w2 = torch.randn(dim * 4, dim) / (dim**0.5) # shape: (dim * 4, dim) # (64, 16)
ffn_b2 = torch.randn(dim) / (dim**0.5) # shape: (dim)  # (16,)

def encoder_block(emb_pe, w_q, w_k, w_v, w_o, n_heads, gamma, beta, ffn_w1, ffn_b1, ffn_w2, ffn_b2):
    attn_out, weights = multi_head_attention(emb_pe, w_q, w_k, w_v, w_o, n_heads)
    x = layer_norm(emb_pe + attn_out, gamma, beta) # residual connection + layer norm
    ffn_out = feed_forward(x, ffn_w1, ffn_b1, ffn_w2, ffn_b2)
    gamma1 = torch.ones(x.shape[1]) # shape: (dim) -> (16,)
    beta1 = torch.zeros(x.shape[1]) # shape: (dim) -> (16,)
    ffn_out = layer_norm(x + ffn_out, gamma1, beta1) # residual connection + layer norm
    return ffn_out




torch.Size([4, 16])

In [ ]:


pe = positional_encoding(seq_len, dim) # shape: (seq_len, dim)
x = x + pe # shape: (seq_len, dim)

x = encoder_block(x, w_q, w_k, w_v, w_o, n_heads, gamma, beta, ffn_w1, ffn_b1, ffn_w2, ffn_b2)

x.shape


x.shape

IndexError: tensors used as indices must be long, int, byte or bool tensors

In [121]:
vocab_size = 10 
dim = 16
C = torch.randn(vocab_size, dim) / (dim**0.5) # shape: (vocab_size, dim)

tokens = torch.tensor([3, 1, 4, 2]) # shape: (seq_len,)
emb = C[tokens] # shape: (seq_len, dim)

emb

tensor([[ 0.0090, -0.0856, -0.0954, -0.0142, -0.2192,  0.1306,  0.1155, -0.3323,
          0.1277, -0.0715,  0.0838,  0.2930, -0.1010, -0.0816,  0.1871, -0.0488],
        [-0.0411, -0.2429, -0.2577,  0.1618, -0.3646, -0.0704, -0.2575, -0.1721,
          0.0549, -0.4247,  0.3274, -0.4153,  0.4336,  0.1667, -0.2603, -0.3505],
        [-0.1718, -0.5837,  0.0235, -0.0505,  0.7814,  0.0446, -0.1613,  0.0028,
          0.1338,  0.4933, -0.0519, -0.0076,  0.0649,  0.1529,  0.2954, -0.2762],
        [ 0.0525,  0.0075,  0.4273, -0.1814, -0.3633, -0.0119,  0.3749,  0.1358,
          0.1848,  0.3133, -0.1111,  0.2046,  0.0031,  0.2439, -0.0020, -0.0100]])

In [73]:
pe = positional_encoding(3, 16)
pe.shape

torch.Size([3, 16])

In [56]:
torch.manual_seed(1337)

def multi_head_attention(w_q, w_k, w_v):
    score = w_q @ w_k.transpose(-2, -1) # (4, 3, 4) @ (4, 4, 3) -> (4, 3, 3)
    score = score / w_q.shape[-1]**0.5 # shape (4, 3, 3)
    print(w_q.shape[-1])
    weights = F.softmax(score, dim=-1) #shape: (4, 3, 3)
    out = weights @ w_v # shape: (4, 3, 3) @ (1, 3, 4) -> (4, 3, 4)
    out = out.transpose(0, 1)
    out = out.contiguous().view(3, 16)
    w_o = torch.randn(dim, dim) / dim**0.5 
    final = out @ w_o
    return final, weights

n_heads = 4
dim = 16
d_k = dim 
emb = torch.randn(3, dim) # shape (3, 16)

q = torch.randn(dim, d_k) # shape: (16, 16)
k = torch.randn(dim, d_k) # shape: (16, 16)
v = torch.randn(dim, d_k) # shape: (16, 16)

w_q = (emb @ q) / dim**0.5 # shape: (3, 16) @ (16, 16) -> (3, 16)
w_q = w_q.view(3, 4, 4) # shape: (3, 4, 4)
w_q = w_q.transpose(0, 1) # shape: (4, 3, 4)

w_k = (emb @ k) / dim**0.5 # shape: (3, 16) @ (16, 16) -> (3, 16)
w_k = w_k.view(3, 4, 4) # shape: (3, 4, 4)
w_k = w_k.transpose(0, 1) # shape: (4, 3, 4)

w_v = (emb @ v) / dim**0.5 # shape: (3, 16) @ (16, 16) -> (3, 4)
w_v = w_v.view(3, 4, 4) # shape: (3, 4, 4)
w_v = w_v.transpose(0, 1) # shape: (4, 3, 4)

final, weights = multi_head_attention(w_q, w_k , w_v)
# print(weights)

print(final)

4
tensor([[-0.5622, -0.0689, -0.5251, -0.1137,  0.5926, -0.8697,  0.2406, -0.6423,
          1.2383, -0.0178, -0.4227, -0.4045, -0.2417, -0.3584, -0.8382,  0.1385],
        [-0.8624, -0.0181, -0.6726, -0.2521,  0.8008, -1.1391,  0.3890, -0.4301,
          1.5162,  0.1845, -0.6071, -0.7263, -0.4845, -0.3257, -0.9650,  0.4652],
        [-0.1983,  0.6396,  0.2315,  0.0620,  0.0722, -0.5628,  0.9176, -0.4640,
          1.6510,  0.3690,  0.0854,  0.4092,  0.1895, -0.1311, -0.0268,  0.5125]])


In [58]:
pos = torch.arange(3).unsqueeze(1)
pos.shape

torch.Size([3, 1])

In [63]:
i = torch.arange(0, dim, 2)
freq = 1.0 / (10000 ** (i / dim))

2 * 3.1459 / freq

tensor([6.2918e+00, 1.9896e+01, 6.2918e+01, 1.9896e+02, 6.2918e+02, 1.9896e+03,
        6.2918e+03, 1.9896e+04])

In [66]:
angles = pos * freq
angles.shape

torch.Size([3, 8])

In [68]:
pe = torch.zeros(3, dim)
pe[ :, 0::2] = torch.sin(angles)
pe[ :, 1::2] = torch.cos(angles)

pe.shape

torch.Size([3, 16])

In [74]:
pe = torch.zeros(3, dim)

In [75]:
pe

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])